// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6axegCGWow4IYyCLKsgSIqAEl8EvY_0',
    appId: '1:975092273023:android:e27b8e7011c4bf32e8944a',
    messagingSenderId: '975092273023',
    projectId: 'financeapp-f9e8a',
    databaseURL: 'https://financeapp-f9e8a-default-rtdb.firebaseio.com',
    storageBucket: 'financeapp-f9e8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGafnYNj4K7oaQuo0e3Vnz4r8bbFJeKz8',
    appId: '1:975092273023:ios:6027320b1c2e157ee8944a',
    messagingSenderId: '975092273023',
    projectId: 'financeapp-f9e8a',
    databaseURL: 'https://financeapp-f9e8a-default-rtdb.firebaseio.com',
    storageBucket: 'financeapp-f9e8a.appspot.com',
    iosClientId: '975092273023-sdcvvm6afu9b1iim386of1mdjlcqor5s.apps.googleusercontent.com',
    iosBundleId: 'com.antonioarista.financeApp',
  );
}
